services:
    postgres:
        image: postgres:latest
        container_name: dev_postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        env_file:
            - ../../apps/web/.env
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
